"""create patient

Revision ID: 685ec2ff50a7
Revises: 
Create Date: 2023-08-21 00:13:01.085296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685ec2ff50a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_first_name', sa.String(), nullable=True),
    sa.Column('patient_last_name', sa.String(), nullable=True),
    sa.Column('patient_phone', sa.String(), nullable=True),
    sa.Column('patient_next_appointment', sa.Date(), nullable=True),
    sa.Column('patient_balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient')
    # ### end Alembic commands ###
