"""adds appointment relationships

Revision ID: 6a471272be40
Revises: c6d7296ee368
Create Date: 2023-09-03 15:34:29.899564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a471272be40'
down_revision: Union[str, None] = 'c6d7296ee368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('actual_doctor')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_doctor', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
