"""adds doctor table

Revision ID: 9c06e588cc3d
Revises: aa0d9d91a972
Create Date: 2023-08-26 17:47:22.402492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c06e588cc3d'
down_revision: Union[str, None] = 'aa0d9d91a972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_first_name', sa.String(), nullable=False),
    sa.Column('doctor_last_name', sa.String(), nullable=False),
    sa.Column('doctor_specialty', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor')
    # ### end Alembic commands ###
