"""creates patient table

Revision ID: c15027ab177d
Revises: 
Create Date: 2023-08-22 11:32:20.425524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15027ab177d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_first_name', sa.String(), nullable=False),
    sa.Column('patient_last_name', sa.String(), nullable=False),
    sa.Column('patient_phone', sa.String(), nullable=False),
    sa.Column('patient_next_appointment', sa.DateTime(), nullable=True),
    sa.Column('patient_created_date', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=True),
    sa.Column('patient_last_updated', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient')
    # ### end Alembic commands ###
