"""add relationship

Revision ID: d80c536e37cf
Revises: d4a9542664e3
Create Date: 2023-08-27 17:54:16.659511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd80c536e37cf'
down_revision: Union[str, None] = 'd4a9542664e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("doctor_patients", 'doctor', ['doctor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint("doctor_patients", type_='foreignkey')
        batch_op.drop_column('doctor_id')

    # ### end Alembic commands ###
