"""format datetime

Revision ID: e65cb1b9bfdb
Revises: aa0d9d91a972
Create Date: 2023-08-24 17:48:27.976420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e65cb1b9bfdb'
down_revision: Union[str, None] = 'aa0d9d91a972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
